### ISSUE TITLE
[Proposal] Changes to the public API

### ISSUE THREAD

**Issue by msaraiva** [msaraiva/surface#106]
Before releasing our first stable version, I'd like to propose a few changes to the API: 

1. Rename the `property` function to just `prop`. 
**Reason:** We're already using `:props`, `__props__`, `__get_prop__` everywhere so let's make it more consistent.

1. Rename all `:on-phx-*` directives to just `:on-*`, e.g. instead of `:on-phx-click`, just `:on-click`.
**Reason:** Surface is already an abstraction on top of LV so I think it's pretty clear that `:on-*` is related to the `phx` bindings.

1. ~Rename `context set` and `context get` to `context_set` and `context_get`.
**Reason:** Simpler implementation, better formatting when not using `import_deps`, better tooling (upcoming autocomplete support)~

**Comment by lnr0626** [comment]
We should also consider always adding an `id` property for `Surface.LiveComponent`s, currently we only add that property if the module exports a `handle_event`, but everywhere else we treat `Surface.LiveComponent` as if they are stateful.

This means that if you don't define a `handle_event` function, and use a property of type `event`, then you'll get an error because it tries to use `@myself`; which is only created when the component has an id.

We should also consider changing the type of the id props we inject to `:string` instead of `:integer`.
