### ISSUE TITLE
Question about nested slots

### ISSUE THREAD

**Issue by Menkir** [msaraiva/surface#158]
Hey guys,
i notices something strange. I defined a named slot (Surface.Component) and implemented a render() function. My goal is to hide information as much as possible to increase the readability. I outsource therefore a particular piece of functionality to that slot and add another <slot/> inside the defined slot.  Basically nested Slots. But this actually doesn't work.
Example: 

## page_live.ex
```
defmodule PageLive do
 use Surface.LiveView
 slot header
 slot body
 slot footer
 def render(assigns) do
  ~H"""
  <Modal id="mymodal">
   <Header>...</Header>
 
   <Body>...</Body>
   
   <Footer>
    <Button event="cancel">Cancel</Button>
   </Footer>
  </Modal>
  """
 end

# callback handling ...
end
```

## modal.ex
```
defmodule Modal do
 use Surface.LiveComponent
 slot header
 slot body
 slot footer

 def render(assigns) do
 ~H"""
 ...
 <slot name="header"/>
...
 <slot name="body"/>
...
 <slot name="footer"/>
 """
 end
end
```

## footer.ex
```
defmodule Footer do
 use Surface.Component, slot: "footer"
 def render(assigns) do
  ~H"""
    <footer>
    <slot/>
   </footer>
  """
 end
end
```

## button.ex
```
defmodule Button do
 use Surface.Component
 prop event, :string, required: true
 def render(assigns) do
 ~H"""
  <button :on-click={{ @event }} class="...">
   <slot/>
  </button>
 """
 end
end
```
The footer-tag around the default slot is not rendered and i don't know why. In the docs it's not explicitly said that this is not possible. When i remove the slot definition of the Footer and call only \<slot/> in Modal then it works.

**Comment by msaraiva** [comment]
Hi @Menkir!

Let's start with the LiveView. They're not supposed to accept `slot`. You should get an error like `undefined function slot/1`. Please let me know if you don't. So your LV should be just:

```elixir
defmodule PageLive do
 use Surface.LiveView

 def render(assigns) do
  ~H"""
  <Modal id="mymodal">
   <Header>...</Header>
 
   <Body>...</Body>
   
   <Footer>
    <Button event="cancel">Cancel</Button>
   </Footer>
  </Modal>
  """
 end

# callback handling ...
end
```

The `Footer` is what we call a renderless component. Whenever you use the `:slot` option as you did in `slot: "footer"`, your component automatically becomes renderless and the `render/1` callback will have no effect. It will be rendered by the parent component using `<slot name="footer">`. So your `footer.ex` should be just:

```elixir
defmodule Footer do
 use Surface.Component, slot: "footer"
end
```

Now since the parent component (the Modal) will be responsible for all the rendering, you need to move any code there. Something like:

```elixir
defmodule Modal do
  use Surface.LiveComponent

  slot header
  slot body
  slot footer
 
  def render(assigns) do
    ~H"""
    ...
    <slot name="header"/>
    ...
    <slot name="body"/>
    ...
    <footer :if={{ assigns[:footer] }}>
      <slot name="footer"/>
    </footer>
    """
  end
end
```

The `:if={{ assigns[:footer] }}` should be used in case you don't want to render an empty `<footer></footer>` when no footer is passed, otherwise, you can remove it.

**Comment by Menkir** [comment]
Ah, got it! Thank you for the quick response :)
