### ISSUE TITLE
Show changeset errors in Form

### ISSUE THREAD

**Issue by iacobson** [msaraiva/surface#180]
In a "normal" Phoenix form you can show the field errors with
`<%= error_tag form, :field %>`

Is there a way to do this in `surface`?

I tried something like

```elixir
<Form for={{@changeset}}  ... > 
...
  {{ MyAppWeb.ErrorHelpers.error_tag(@form, :my_field) }}
</Form>
```

But I do not know how to get the `@form`.
Or is there a nicer way to do it?

**Comment by msaraiva** [comment]
Hi @iacobson!

You can use `<Context/>` to retrieve the generated form instance from the context:

```jsx
<Form for={{@changeset}}  ... > 
  <Context get={{ Form, form: f }}>
    ...
    {{ MyAppWeb.ErrorHelpers.error_tag(f, :my_field) }}
  </Context>
</Form>
```

However, we should definitely expose the generated form as a slot prop so you could do this instead:

```jsx
<Form for={{@changeset}} :let={{ form: f }}> 
  ...
  {{ MyAppWeb.ErrorHelpers.error_tag(f, :my_field) }}
</Form>
```

I'll open an issue for it.

In either case, the best solution, IMO, would be to create a new component `<ErrorTag>` or `<FieldError>` that could retrieve the form from the context automatically so you could use it as:

```jsx
<Form for={{@changeset}}  ... > 
  ...
  <FieldError field="my_field"/>
</Form>
```

and in case you're already using `<Field>` or `<FieldContext>`, you could do just:

```jsx
<Form for={{@changeset}}  ... > 
  ...
  <Field name="my_field">
    ...
    <FieldError/>
  </Field>
</Form>
```

**Comment by msaraiva** [comment]
Closed in favour of https://github.com/msaraiva/surface/issues/181.

**Comment by iacobson** [comment]
Thanks! tried your first suggestion and works.
When you are saying creating a new component `<FieldError/>` do you mean it as a `surface` library component, or as a best practice for users to implement in their projects?

**Comment by msaraiva** [comment]
It's hard to add a `<FieldError/>` to Surface's core lib because we usually have many different ways to show errors across all different projects and CSS libs so I think this should be customized per project. One requirement we have when adding a new component to the core is that it cannot force us to make any assumption regarding the design (markup structure, css, js, etc.). 

Having said that, we can still take advantage of the component model + contexts and abstract that logic into a separate component. I wouldn't say it's a best practice. There's nothing wrong in using components and functions together but in this case, since all other form components can handle contexts property, it seems to me that having also the error renderer doing the same makes the code more consistent and clean as all form controls can work the same way. Besides, the implementation is quite simple. Something like this should work:

```elixir
defmodule FieldError do
  use Surface.Component

  alias Surface.Components.Form.Input.InputContext

  @doc "The form instance"
  prop form, :form

  @doc "An identifier for the field"
  prop field, :atom

  def render(assigns) do
    ~H"""
    <InputContext assigns={{ assigns }} :let={{ form: form, field: field }}>
      {{ MyAppWeb.ErrorHelpers.error_tag(form, field) }}
    </InputContext>
    """
  end
end
```

Using `InputContext` is nice because it automatically handles fallback values (props `form` and `field`) in case you don't want to use contexts.
 
But again, it's totally optional :)
