### ISSUE TITLE
Convert some warnings to compile error

### ISSUE THREAD

**Issue by Malian** [msaraiva/surface#239]
During the review of the dead code in #237 I noticed that the message of some warnings force the user to resolve the issue.

For example:
https://github.com/msaraiva/surface/blob/2286f8b6130679f60fd5ece18251d3f84a1dd830/lib/surface/compiler.ex#L149-L160

I believe this kind of warnings should be converted to a `CompileError`.

An other example is in the `to_ast` function:
https://github.com/msaraiva/surface/blob/2286f8b6130679f60fd5ece18251d3f84a1dd830/lib/surface/compiler.ex#L167-L183

Any reasons why we return a warning + an `AST.Error` instead of a `CompileError`?

**Comment by msaraiva** [comment]
Regarding the first one, I think it's because this is a LV related issue, i.e. we don't have any code/feature that depend on that condition (single root node) so we only add those warnings at compile-time to give faster feedback to the user as Phoenix will only raise an error at runtime. So it seems it would be too strict to add a hard error for something that we don't own. If phoenix changes that behaviour in the future (there has been some discussions already), we'll have a breaking change. BTW, I don't have a strong option on this one. It more like a feeling that is better this way. I might change my mind :)

Regarding the second one, I believe we prefer warnings in this case because since each node in the tree is usually independent from each other, those errors are mostly not related, so having them as warnings allows the user to fix several of them at once, instead of fixing one, compiling it, fix another one, compiling it again.

@lnr0626 do you agree?

**Comment by lnr0626** [comment]
Agreed. I think the first would also cause issues with the `:debug` directive until we've fixed #142

**Comment by Malian** [comment]
Thanks both for the explanations! I close the issue.
