### ISSUE TITLE
Docs recommendation regarding adding  `.sface` to the watchers list

### ISSUE THREAD

**Issue by gavriguy** [msaraiva/surface#247]
Hi, Great library 👍 

In the `Colocated templates` section in the docs I think it will be nice to recommend  developers to add `.sface` files to the watchers list inside the `dev.exs` file. e.g.

```
config : MyApp, MyAppWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/.*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/zapp2_web/(live|views)/.*(ex)$",
      ~r"lib/zapp2_web/templates/.*(eex)$",
      ~r"lib/zapp2_web/live/.*(sface)$"
    ]
  ]

```

I would have added a PR myself but I can't find the docs repo

**Comment by msaraiva** [comment]
Hi @gavriguy!

Thanks for pointing that out. Since this is a configuration, I think we should probably add it to the [Getting Started](http://surface-demo.msaraiva.io/getting_started) section, along with the other configs. WDYT? Something like:

---

...

If you're using `mix format`, make sure you add `surface` to the `import_deps` configuration in your `.formatter.exs` file:

```
[
  import_deps: [:ecto, :phoenix, :surface],
  ...
]
```

To allow live reloading for `.sface` files, add the related patterns to the endpoint configuration in your `config/dev.exs`:

```
config : MyApp, MyAppWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"lib/my_app_web/live/.*(sface)$",
      ...
    ]
  ]
```
...

**Comment by gavriguy** [comment]
Sounds good. Thank you :)

**Comment by msaraiva** [comment]
OK. I added it. It will be available as soon as I finish updating a few other things in the docs before releasing `v0.1.2`. I'll leave the issue open until the release.

Cheers.

**Comment by msaraiva** [comment]
Already pushed to the new [repo](https://github.com/surface-ui/surface_site/blob/d2fe5f79f2bf178bcc1d9761f5f44c3beed971a0/lib/surface_site_web/live/getting_started.ex#L60-L71).
