### ISSUE TITLE
surface demo documentation code

### ISSUE THREAD

**Issue by zven21** [msaraiva/surface#248]
Hi @msaraiva ,  Nice library.

I'm already using it in production and working on a set of UI libraries based on surface.

I plan to open source him:

* This is project: [surface_antd](https://github.com/hc360-elixir/surface_antd)
* This is my goal [antd](https://ant.design/components/overview/)
* This is my progress [to-do’s](https://github.com/hc360-elixir/surface_antd/blob/master/lib/components/README.md)

I'm currently writing a doc, can I use the source code from the [surface_demo](http://surface-demo.msaraiva.io/uicomponents) site?

Thank you.

**Comment by msaraiva** [comment]
Hi @zven21!

It's great to see Surface being used in production. Great work on the library!

> I'm currently writing a doc, can I use the source code from the surface_demo site?

I'm about to make public an experimental project called `surface_catalogue`, which has the same basic components used in the surface demo. Including the on-the-fly Docs/API generator with some additional cool features. In fact, the goal is to update the demo with the new components as they are more flexible and will allow less maintenance as the examples will also be extracted directly from the lib source, instead of manually added/updated. You can certainly use/adapt any component you want for your needs. I'm on vacation now but I'll try to wrap up the project this week so you can take a look. I'll let you know when it's available.

Cheers.

**Comment by zven21** [comment]
@msaraiva im looking forward to `surface_catalogue `,  thanks for your reply.

**Comment by msaraiva** [comment]
@zven21 since the `surface_catalogue` may still take a few days to turn public, I gave you access to the `surface_site` project. Feel free to make use of any component you might need. Pay attention that most of those components were developed just to build the website so they may not be full-featured nor fully documented.

**Comment by zven21** [comment]
@msaraiva thank you. :smile:
