### ISSUE TITLE
Question: can I translate a string?

### ISSUE THREAD

**Issue by mazz-seven** [msaraiva/surface#35]
Hey,
I'm playing with Surface and I wonder if I can translate a string after loading it from a file?

Say I loaded this string.
"<Custom>Hello World</Custom>"
How can I use Surface to translate it and resolve the custom component?

Thanks 
— Mazz

**Comment by msaraiva** [comment]
Hi @mazz-seven!

I'm not sure I fully understood what you need but if you want a way to apply some kind of custom translation at compile-time, you need to use the low level `MacroComponent`. For instance, imagine you want to write a component that translates markdown content into HTML, you could do something like this:

```elixir
defmodule Markdown do
  use Surface.MacroComponent

  def translate({_, _, children, _}, _caller) do
    markdown =
      children
      |> IO.iodata_to_binary()
      |> String.split("\n")
      |> Enum.map(&String.trim_leading/1)
      |> Enum.join("\n")

    html =
      case Earmark.as_html(markdown) do
        {:ok, html, messages} ->
          Enum.each(messages, fn msg -> IO.warn(msg) end)
          html
        {:error, html, messages} ->
          Enum.each(messages, fn msg -> IO.warn(msg) end)
          html
      end
    {[], [~S(<div class="content" style="margin-top: 2em;">), html, "</div>"], []}
  end
end
```

in order to use macro components you need to prefix them with `#`:

```html
<div>
  <#Markdown>
    # Title

    This text will be translated from **markdown** to **html**. Cool!
  <#Markdown>
</div>
```

You have probably seen a macro component in the examples, the built-in `<#Raw>` which just skip translation and render whatever the content is.

Let me know if this is somehow what you need.

**Comment by mazz-seven** [comment]
Hi @msaraiva 
What if inside the Markdown I want to use a Surface component?

**Comment by msaraiva** [comment]
It's possible but it requires a tiny change in the translator. I need to make some tests. I'll let you know.

**Comment by mazz-seven** [comment]
Thanks

**Comment by msaraiva** [comment]
@mazz-seven in case you're still interested, we have just merged the new compiler so I believe this could be achieved now. Let me know if it doesn't.
