### ISSUE TITLE
Migrate to Hex and Releases

### ISSUE THREAD

**Issue by wrren** [msaraiva/surface#38]
I'm loving Surface so far, but in order to use it in my projects more reliably I think it'll need to move to Hex and concrete releases. The current approach of importing through Git means that any breakages in `master` will affect everyone who runs `mix deps.get` after that point. If you'd like any help with the release generation and Hex publishing process then I'd be happy to help.

**Comment by msaraiva** [comment]
Hey @wrren!

As soon as I merge #29 (probably tomorrow), I'll release a `v0.1.0-alpha.0`

**Comment by msaraiva** [comment]
Surface `v0.1.0-alpha.0` has been published and it's available at https://hex.pm/packages/surface.

**Comment by leanersoft** [comment]
For those who want to use functionality not yet available on hex while keeping some control, a specific commit can be set in mix.exs:

```elixir
  defp deps do
    [
      {:surface, github: "msaraiva/surface", ref: "4fb6f55f0243c7fad903ddd922a4c6667a46be02"},
      # ...
    ]
  end
```

**Comment by wrren** [comment]
@msaraiva it would be great if a release candence could be established; there have been many fixes and changes incorporated since the last one!

**Comment by msaraiva** [comment]
Hi @wrren!

The lastest merged changes demanded a lot of work in the docs & examples. I'm also rewriting the whole demo website to provide a better experience to the user. I'll release a new version as soon as I finish that work. Otherwise, it's going to be hard for new users to follow the docs/examples if they are out of sync with the latest released version. I just need a couple of hours to update a few things due to some recent changes in LiveView v0.11.0 and I'll ready to push a new `alpha.1`.

**Comment by wrren** [comment]
Nice! Can't wait for the new release :)
