### ISSUE TITLE
phx-hook question

### ISSUE THREAD

**Issue by lnr0626** [msaraiva/surface#39]
I'm considering using this in my application; however can't find any documentation on how phx-hook interacts with the generated code. I assume that this would just work correctly as long as the attribute were added to the actual html element (i.e. not a surface component) i.e.:

```elixir
  defmodule Hello do
    use Surface.Component

    def render(assigns) do
      ~H"""
      <span phx-hook="HelloHook">Hello, I'm a component!</span>
      """
    end
  end
```

is that accurate?

Thank you for the work you've put into this; it looks really solid!

**Comment by msaraiva** [comment]
Hi @lnr0626!

That's accurate.

You can use any available `phx-*` in your HTML tags. There's also some directives offered by Surface that makes working with events more intuitive and less verbose, e.g. `:on-phx-click` and friends. For `phx-hook`, however, there's no wrapper directive since its usage is straightforward and requires no extra abstraction.

**Comment by lnr0626** [comment]
awesome, thanks for the quick response!
