### ISSUE TITLE
Question: Propagating events up through component hierarchy without being hacky

### ISSUE THREAD

**Issue by mindok** [msaraiva/surface#99]
I have been building a table component with paging and row selection. I have implemented a row selection event using a property of type :event, but it isn't satisfactory for two reasons:
1. When I change page, I'd like to automatically fire the "row-selection" event to for the first row in the page - I can't see how to invoke the event from the table without doing some low-level hack
2. I'd like to be able to set a selected row-id or similar in the table component so I can change the display class (e.g. add `is-selected` using Bulma) without the implementation leaking to the host liveview.

Server-side invocation of events within the table component would solve for both of these. My plan at the moment is to trawl the liveview and its test infrastructure code and figure out how to manually package and send a `Phoenix.Socket.Message` to do this but wanted to first check if there was an easier way!

**Comment by msaraiva** [comment]
Hi @mindok!

The `:event` type only indicates that instead of using just a string for the event, Surface will use a map that holds both, the event and the target (which is `@myself` by default). This way you don't need to pass both using `phx-[event]` + `phx-target` in most of the situations. After the code is translated, the behaviour is exactly like using LiveView's `live_component/3` directly.

Regarding server-side invocation of events, it's not clear to me what you have in mind but I believe you don't even need that. Have you tried using [send_update/2](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#send_update/2) to update the state of the components?

I'm not sure this is the answer you were expecting. Maybe I have misunderstood the problem. If that's the case, can you provide some snippets of the related code? I might be able to come up with a better answer if I see some code :)

**Comment by mindok** [comment]
Thanks @msaraiva - I'll have a bit more of an experiment. I'm not sure `send_update` will work as I want to invoke the event on the containing LiveView rather than the component. If I get something working nicely I'll update this issue, and if not, I'll post some sample code and a few more details.

**Comment by msaraiva** [comment]
Closing this for now.

@mindok feel free to reopen it if needed.
